// Package network provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package network

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ACLRuleAction.
const (
	ACLRuleActionALLOW ACLRuleAction = "ALLOW"
	ACLRuleActionBLOCK ACLRuleAction = "BLOCK"
)

// Valid indicates whether the value is a known member of the ACLRuleAction enum.
func (e ACLRuleAction) Valid() bool {
	switch e {
	case ACLRuleActionALLOW:
		return true
	case ACLRuleActionBLOCK:
		return true
	default:
		return false
	}
}

// Defines values for ACLRuleUpdateAction.
const (
	ACLRuleUpdateActionALLOW ACLRuleUpdateAction = "ALLOW"
	ACLRuleUpdateActionBLOCK ACLRuleUpdateAction = "BLOCK"
)

// Valid indicates whether the value is a known member of the ACLRuleUpdateAction enum.
func (e ACLRuleUpdateAction) Valid() bool {
	switch e {
	case ACLRuleUpdateActionALLOW:
		return true
	case ACLRuleUpdateActionBLOCK:
		return true
	default:
		return false
	}
}

// Defines values for ACLRuleObjectAction.
const (
	ACLRuleObjectActionALLOW ACLRuleObjectAction = "ALLOW"
	ACLRuleObjectActionBLOCK ACLRuleObjectAction = "BLOCK"
)

// Valid indicates whether the value is a known member of the ACLRuleObjectAction enum.
func (e ACLRuleObjectAction) Valid() bool {
	switch e {
	case ACLRuleObjectActionALLOW:
		return true
	case ACLRuleObjectActionBLOCK:
		return true
	default:
		return false
	}
}

// Defines values for AdoptedDeviceDetailsState.
const (
	AdoptedDeviceDetailsStateADOPTING              AdoptedDeviceDetailsState = "ADOPTING"
	AdoptedDeviceDetailsStateCONNECTIONINTERRUPTED AdoptedDeviceDetailsState = "CONNECTION_INTERRUPTED"
	AdoptedDeviceDetailsStateDELETING              AdoptedDeviceDetailsState = "DELETING"
	AdoptedDeviceDetailsStateGETTINGREADY          AdoptedDeviceDetailsState = "GETTING_READY"
	AdoptedDeviceDetailsStateISOLATED              AdoptedDeviceDetailsState = "ISOLATED"
	AdoptedDeviceDetailsStateOFFLINE               AdoptedDeviceDetailsState = "OFFLINE"
	AdoptedDeviceDetailsStateONLINE                AdoptedDeviceDetailsState = "ONLINE"
	AdoptedDeviceDetailsStatePENDINGADOPTION       AdoptedDeviceDetailsState = "PENDING_ADOPTION"
	AdoptedDeviceDetailsStateU5GINCORRECTTOPOLOGY  AdoptedDeviceDetailsState = "U5G_INCORRECT_TOPOLOGY"
	AdoptedDeviceDetailsStateUPDATING              AdoptedDeviceDetailsState = "UPDATING"
)

// Valid indicates whether the value is a known member of the AdoptedDeviceDetailsState enum.
func (e AdoptedDeviceDetailsState) Valid() bool {
	switch e {
	case AdoptedDeviceDetailsStateADOPTING:
		return true
	case AdoptedDeviceDetailsStateCONNECTIONINTERRUPTED:
		return true
	case AdoptedDeviceDetailsStateDELETING:
		return true
	case AdoptedDeviceDetailsStateGETTINGREADY:
		return true
	case AdoptedDeviceDetailsStateISOLATED:
		return true
	case AdoptedDeviceDetailsStateOFFLINE:
		return true
	case AdoptedDeviceDetailsStateONLINE:
		return true
	case AdoptedDeviceDetailsStatePENDINGADOPTION:
		return true
	case AdoptedDeviceDetailsStateU5GINCORRECTTOPOLOGY:
		return true
	case AdoptedDeviceDetailsStateUPDATING:
		return true
	default:
		return false
	}
}

// Defines values for AdoptedDeviceOverviewFeatures.
const (
	AdoptedDeviceOverviewFeaturesAccessPoint AdoptedDeviceOverviewFeatures = "accessPoint"
	AdoptedDeviceOverviewFeaturesGateway     AdoptedDeviceOverviewFeatures = "gateway"
	AdoptedDeviceOverviewFeaturesSwitching   AdoptedDeviceOverviewFeatures = "switching"
)

// Valid indicates whether the value is a known member of the AdoptedDeviceOverviewFeatures enum.
func (e AdoptedDeviceOverviewFeatures) Valid() bool {
	switch e {
	case AdoptedDeviceOverviewFeaturesAccessPoint:
		return true
	case AdoptedDeviceOverviewFeaturesGateway:
		return true
	case AdoptedDeviceOverviewFeaturesSwitching:
		return true
	default:
		return false
	}
}

// Defines values for AdoptedDeviceOverviewInterfaces.
const (
	Ports  AdoptedDeviceOverviewInterfaces = "ports"
	Radios AdoptedDeviceOverviewInterfaces = "radios"
)

// Valid indicates whether the value is a known member of the AdoptedDeviceOverviewInterfaces enum.
func (e AdoptedDeviceOverviewInterfaces) Valid() bool {
	switch e {
	case Ports:
		return true
	case Radios:
		return true
	default:
		return false
	}
}

// Defines values for AdoptedDeviceOverviewState.
const (
	AdoptedDeviceOverviewStateADOPTING              AdoptedDeviceOverviewState = "ADOPTING"
	AdoptedDeviceOverviewStateCONNECTIONINTERRUPTED AdoptedDeviceOverviewState = "CONNECTION_INTERRUPTED"
	AdoptedDeviceOverviewStateDELETING              AdoptedDeviceOverviewState = "DELETING"
	AdoptedDeviceOverviewStateGETTINGREADY          AdoptedDeviceOverviewState = "GETTING_READY"
	AdoptedDeviceOverviewStateISOLATED              AdoptedDeviceOverviewState = "ISOLATED"
	AdoptedDeviceOverviewStateOFFLINE               AdoptedDeviceOverviewState = "OFFLINE"
	AdoptedDeviceOverviewStateONLINE                AdoptedDeviceOverviewState = "ONLINE"
	AdoptedDeviceOverviewStatePENDINGADOPTION       AdoptedDeviceOverviewState = "PENDING_ADOPTION"
	AdoptedDeviceOverviewStateU5GINCORRECTTOPOLOGY  AdoptedDeviceOverviewState = "U5G_INCORRECT_TOPOLOGY"
	AdoptedDeviceOverviewStateUPDATING              AdoptedDeviceOverviewState = "UPDATING"
)

// Valid indicates whether the value is a known member of the AdoptedDeviceOverviewState enum.
func (e AdoptedDeviceOverviewState) Valid() bool {
	switch e {
	case AdoptedDeviceOverviewStateADOPTING:
		return true
	case AdoptedDeviceOverviewStateCONNECTIONINTERRUPTED:
		return true
	case AdoptedDeviceOverviewStateDELETING:
		return true
	case AdoptedDeviceOverviewStateGETTINGREADY:
		return true
	case AdoptedDeviceOverviewStateISOLATED:
		return true
	case AdoptedDeviceOverviewStateOFFLINE:
		return true
	case AdoptedDeviceOverviewStateONLINE:
		return true
	case AdoptedDeviceOverviewStatePENDINGADOPTION:
		return true
	case AdoptedDeviceOverviewStateU5GINCORRECTTOPOLOGY:
		return true
	case AdoptedDeviceOverviewStateUPDATING:
		return true
	default:
		return false
	}
}

// Defines values for BlackoutScheduleConfigurationPerDayDay.
const (
	FRI BlackoutScheduleConfigurationPerDayDay = "FRI"
	MON BlackoutScheduleConfigurationPerDayDay = "MON"
	SAT BlackoutScheduleConfigurationPerDayDay = "SAT"
	SUN BlackoutScheduleConfigurationPerDayDay = "SUN"
	THU BlackoutScheduleConfigurationPerDayDay = "THU"
	TUE BlackoutScheduleConfigurationPerDayDay = "TUE"
	WED BlackoutScheduleConfigurationPerDayDay = "WED"
)

// Valid indicates whether the value is a known member of the BlackoutScheduleConfigurationPerDayDay enum.
func (e BlackoutScheduleConfigurationPerDayDay) Valid() bool {
	switch e {
	case FRI:
		return true
	case MON:
		return true
	case SAT:
		return true
	case SUN:
		return true
	case THU:
		return true
	case TUE:
		return true
	case WED:
		return true
	default:
		return false
	}
}

// Defines values for CreateOrUpdateFirewallPolicyConnectionStateFilter.
const (
	CreateOrUpdateFirewallPolicyConnectionStateFilterESTABLISHED CreateOrUpdateFirewallPolicyConnectionStateFilter = "ESTABLISHED"
	CreateOrUpdateFirewallPolicyConnectionStateFilterINVALID     CreateOrUpdateFirewallPolicyConnectionStateFilter = "INVALID"
	CreateOrUpdateFirewallPolicyConnectionStateFilterNEW         CreateOrUpdateFirewallPolicyConnectionStateFilter = "NEW"
	CreateOrUpdateFirewallPolicyConnectionStateFilterRELATED     CreateOrUpdateFirewallPolicyConnectionStateFilter = "RELATED"
)

// Valid indicates whether the value is a known member of the CreateOrUpdateFirewallPolicyConnectionStateFilter enum.
func (e CreateOrUpdateFirewallPolicyConnectionStateFilter) Valid() bool {
	switch e {
	case CreateOrUpdateFirewallPolicyConnectionStateFilterESTABLISHED:
		return true
	case CreateOrUpdateFirewallPolicyConnectionStateFilterINVALID:
		return true
	case CreateOrUpdateFirewallPolicyConnectionStateFilterNEW:
		return true
	case CreateOrUpdateFirewallPolicyConnectionStateFilterRELATED:
		return true
	default:
		return false
	}
}

// Defines values for CreateOrUpdateFirewallPolicyIpsecFilter.
const (
	CreateOrUpdateFirewallPolicyIpsecFilterMATCHENCRYPTED    CreateOrUpdateFirewallPolicyIpsecFilter = "MATCH_ENCRYPTED"
	CreateOrUpdateFirewallPolicyIpsecFilterMATCHNOTENCRYPTED CreateOrUpdateFirewallPolicyIpsecFilter = "MATCH_NOT_ENCRYPTED"
)

// Valid indicates whether the value is a known member of the CreateOrUpdateFirewallPolicyIpsecFilter enum.
func (e CreateOrUpdateFirewallPolicyIpsecFilter) Valid() bool {
	switch e {
	case CreateOrUpdateFirewallPolicyIpsecFilterMATCHENCRYPTED:
		return true
	case CreateOrUpdateFirewallPolicyIpsecFilterMATCHNOTENCRYPTED:
		return true
	default:
		return false
	}
}

// Defines values for DevicePendingAdoptionFeatures.
const (
	DevicePendingAdoptionFeaturesAccessPoint DevicePendingAdoptionFeatures = "accessPoint"
	DevicePendingAdoptionFeaturesGateway     DevicePendingAdoptionFeatures = "gateway"
	DevicePendingAdoptionFeaturesSwitching   DevicePendingAdoptionFeatures = "switching"
)

// Valid indicates whether the value is a known member of the DevicePendingAdoptionFeatures enum.
func (e DevicePendingAdoptionFeatures) Valid() bool {
	switch e {
	case DevicePendingAdoptionFeaturesAccessPoint:
		return true
	case DevicePendingAdoptionFeaturesGateway:
		return true
	case DevicePendingAdoptionFeaturesSwitching:
		return true
	default:
		return false
	}
}

// Defines values for DevicePendingAdoptionState.
const (
	ADOPTING              DevicePendingAdoptionState = "ADOPTING"
	CONNECTIONINTERRUPTED DevicePendingAdoptionState = "CONNECTION_INTERRUPTED"
	DELETING              DevicePendingAdoptionState = "DELETING"
	GETTINGREADY          DevicePendingAdoptionState = "GETTING_READY"
	ISOLATED              DevicePendingAdoptionState = "ISOLATED"
	OFFLINE               DevicePendingAdoptionState = "OFFLINE"
	ONLINE                DevicePendingAdoptionState = "ONLINE"
	PENDINGADOPTION       DevicePendingAdoptionState = "PENDING_ADOPTION"
	U5GINCORRECTTOPOLOGY  DevicePendingAdoptionState = "U5G_INCORRECT_TOPOLOGY"
	UPDATING              DevicePendingAdoptionState = "UPDATING"
)

// Valid indicates whether the value is a known member of the DevicePendingAdoptionState enum.
func (e DevicePendingAdoptionState) Valid() bool {
	switch e {
	case ADOPTING:
		return true
	case CONNECTIONINTERRUPTED:
		return true
	case DELETING:
		return true
	case GETTINGREADY:
		return true
	case ISOLATED:
		return true
	case OFFLINE:
		return true
	case ONLINE:
		return true
	case PENDINGADOPTION:
		return true
	case U5GINCORRECTTOPOLOGY:
		return true
	case UPDATING:
		return true
	default:
		return false
	}
}

// Defines values for FirewallPolicyConnectionStateFilter.
const (
	FirewallPolicyConnectionStateFilterESTABLISHED FirewallPolicyConnectionStateFilter = "ESTABLISHED"
	FirewallPolicyConnectionStateFilterINVALID     FirewallPolicyConnectionStateFilter = "INVALID"
	FirewallPolicyConnectionStateFilterNEW         FirewallPolicyConnectionStateFilter = "NEW"
	FirewallPolicyConnectionStateFilterRELATED     FirewallPolicyConnectionStateFilter = "RELATED"
)

// Valid indicates whether the value is a known member of the FirewallPolicyConnectionStateFilter enum.
func (e FirewallPolicyConnectionStateFilter) Valid() bool {
	switch e {
	case FirewallPolicyConnectionStateFilterESTABLISHED:
		return true
	case FirewallPolicyConnectionStateFilterINVALID:
		return true
	case FirewallPolicyConnectionStateFilterNEW:
		return true
	case FirewallPolicyConnectionStateFilterRELATED:
		return true
	default:
		return false
	}
}

// Defines values for FirewallPolicyIpsecFilter.
const (
	FirewallPolicyIpsecFilterMATCHENCRYPTED    FirewallPolicyIpsecFilter = "MATCH_ENCRYPTED"
	FirewallPolicyIpsecFilterMATCHNOTENCRYPTED FirewallPolicyIpsecFilter = "MATCH_NOT_ENCRYPTED"
)

// Valid indicates whether the value is a known member of the FirewallPolicyIpsecFilter enum.
func (e FirewallPolicyIpsecFilter) Valid() bool {
	switch e {
	case FirewallPolicyIpsecFilterMATCHENCRYPTED:
		return true
	case FirewallPolicyIpsecFilterMATCHNOTENCRYPTED:
		return true
	default:
		return false
	}
}

// Defines values for IntegrationWifiBasicDataRateConfigurationDto24.
const (
	IntegrationWifiBasicDataRateConfigurationDto24N1000  IntegrationWifiBasicDataRateConfigurationDto24 = 1000
	IntegrationWifiBasicDataRateConfigurationDto24N11000 IntegrationWifiBasicDataRateConfigurationDto24 = 11000
	IntegrationWifiBasicDataRateConfigurationDto24N12000 IntegrationWifiBasicDataRateConfigurationDto24 = 12000
	IntegrationWifiBasicDataRateConfigurationDto24N2000  IntegrationWifiBasicDataRateConfigurationDto24 = 2000
	IntegrationWifiBasicDataRateConfigurationDto24N24000 IntegrationWifiBasicDataRateConfigurationDto24 = 24000
	IntegrationWifiBasicDataRateConfigurationDto24N5500  IntegrationWifiBasicDataRateConfigurationDto24 = 5500
	IntegrationWifiBasicDataRateConfigurationDto24N6000  IntegrationWifiBasicDataRateConfigurationDto24 = 6000
	IntegrationWifiBasicDataRateConfigurationDto24N9000  IntegrationWifiBasicDataRateConfigurationDto24 = 9000
)

// Valid indicates whether the value is a known member of the IntegrationWifiBasicDataRateConfigurationDto24 enum.
func (e IntegrationWifiBasicDataRateConfigurationDto24) Valid() bool {
	switch e {
	case IntegrationWifiBasicDataRateConfigurationDto24N1000:
		return true
	case IntegrationWifiBasicDataRateConfigurationDto24N11000:
		return true
	case IntegrationWifiBasicDataRateConfigurationDto24N12000:
		return true
	case IntegrationWifiBasicDataRateConfigurationDto24N2000:
		return true
	case IntegrationWifiBasicDataRateConfigurationDto24N24000:
		return true
	case IntegrationWifiBasicDataRateConfigurationDto24N5500:
		return true
	case IntegrationWifiBasicDataRateConfigurationDto24N6000:
		return true
	case IntegrationWifiBasicDataRateConfigurationDto24N9000:
		return true
	default:
		return false
	}
}

// Defines values for IntegrationWifiBasicDataRateConfigurationDto5.
const (
	IntegrationWifiBasicDataRateConfigurationDto5N12000 IntegrationWifiBasicDataRateConfigurationDto5 = 12000
	IntegrationWifiBasicDataRateConfigurationDto5N24000 IntegrationWifiBasicDataRateConfigurationDto5 = 24000
	IntegrationWifiBasicDataRateConfigurationDto5N6000  IntegrationWifiBasicDataRateConfigurationDto5 = 6000
	IntegrationWifiBasicDataRateConfigurationDto5N9000  IntegrationWifiBasicDataRateConfigurationDto5 = 9000
)

// Valid indicates whether the value is a known member of the IntegrationWifiBasicDataRateConfigurationDto5 enum.
func (e IntegrationWifiBasicDataRateConfigurationDto5) Valid() bool {
	switch e {
	case IntegrationWifiBasicDataRateConfigurationDto5N12000:
		return true
	case IntegrationWifiBasicDataRateConfigurationDto5N24000:
		return true
	case IntegrationWifiBasicDataRateConfigurationDto5N6000:
		return true
	case IntegrationWifiBasicDataRateConfigurationDto5N9000:
		return true
	default:
		return false
	}
}

// Defines values for IntegrationWifiClientFilteringPolicyDtoAction.
const (
	IntegrationWifiClientFilteringPolicyDtoActionALLOW IntegrationWifiClientFilteringPolicyDtoAction = "ALLOW"
	IntegrationWifiClientFilteringPolicyDtoActionBLOCK IntegrationWifiClientFilteringPolicyDtoAction = "BLOCK"
)

// Valid indicates whether the value is a known member of the IntegrationWifiClientFilteringPolicyDtoAction enum.
func (e IntegrationWifiClientFilteringPolicyDtoAction) Valid() bool {
	switch e {
	case IntegrationWifiClientFilteringPolicyDtoActionALLOW:
		return true
	case IntegrationWifiClientFilteringPolicyDtoActionBLOCK:
		return true
	default:
		return false
	}
}

// Defines values for LatestStatisticsForWirelessRadioFrequencyGHz.
const (
	LatestStatisticsForWirelessRadioFrequencyGHzN24 LatestStatisticsForWirelessRadioFrequencyGHz = 2.4
	LatestStatisticsForWirelessRadioFrequencyGHzN5  LatestStatisticsForWirelessRadioFrequencyGHz = 5
	LatestStatisticsForWirelessRadioFrequencyGHzN6  LatestStatisticsForWirelessRadioFrequencyGHz = 6
	LatestStatisticsForWirelessRadioFrequencyGHzN60 LatestStatisticsForWirelessRadioFrequencyGHz = 60
)

// Valid indicates whether the value is a known member of the LatestStatisticsForWirelessRadioFrequencyGHz enum.
func (e LatestStatisticsForWirelessRadioFrequencyGHz) Valid() bool {
	switch e {
	case LatestStatisticsForWirelessRadioFrequencyGHzN24:
		return true
	case LatestStatisticsForWirelessRadioFrequencyGHzN5:
		return true
	case LatestStatisticsForWirelessRadioFrequencyGHzN6:
		return true
	case LatestStatisticsForWirelessRadioFrequencyGHzN60:
		return true
	default:
		return false
	}
}

// Defines values for NetworkReferenceResourceResourceType.
const (
	CLIENT      NetworkReferenceResourceResourceType = "CLIENT"
	DEVICE      NetworkReferenceResourceResourceType = "DEVICE"
	NATRULE     NetworkReferenceResourceResourceType = "NAT_RULE"
	NEXTAI      NetworkReferenceResourceResourceType = "NEXT_AI"
	OSPFROUTE   NetworkReferenceResourceResourceType = "OSPF_ROUTE"
	SDWAN       NetworkReferenceResourceResourceType = "SD_WAN"
	STATICROUTE NetworkReferenceResourceResourceType = "STATIC_ROUTE"
	WIFI        NetworkReferenceResourceResourceType = "WIFI"
)

// Valid indicates whether the value is a known member of the NetworkReferenceResourceResourceType enum.
func (e NetworkReferenceResourceResourceType) Valid() bool {
	switch e {
	case CLIENT:
		return true
	case DEVICE:
		return true
	case NATRULE:
		return true
	case NEXTAI:
		return true
	case OSPFROUTE:
		return true
	case SDWAN:
		return true
	case STATICROUTE:
		return true
	case WIFI:
		return true
	default:
		return false
	}
}

// Defines values for PortPoEOverviewStandard.
const (
	N8023af PortPoEOverviewStandard = "802.3af"
	N8023at PortPoEOverviewStandard = "802.3at"
	N8023bt PortPoEOverviewStandard = "802.3bt"
)

// Valid indicates whether the value is a known member of the PortPoEOverviewStandard enum.
func (e PortPoEOverviewStandard) Valid() bool {
	switch e {
	case N8023af:
		return true
	case N8023at:
		return true
	case N8023bt:
		return true
	default:
		return false
	}
}

// Defines values for PortPoEOverviewState.
const (
	PortPoEOverviewStateDOWN    PortPoEOverviewState = "DOWN"
	PortPoEOverviewStateLIMITED PortPoEOverviewState = "LIMITED"
	PortPoEOverviewStateUNKNOWN PortPoEOverviewState = "UNKNOWN"
	PortPoEOverviewStateUP      PortPoEOverviewState = "UP"
)

// Valid indicates whether the value is a known member of the PortPoEOverviewState enum.
func (e PortPoEOverviewState) Valid() bool {
	switch e {
	case PortPoEOverviewStateDOWN:
		return true
	case PortPoEOverviewStateLIMITED:
		return true
	case PortPoEOverviewStateUNKNOWN:
		return true
	case PortPoEOverviewStateUP:
		return true
	default:
		return false
	}
}

// Defines values for PortPoEOverviewType.
const (
	N1 PortPoEOverviewType = 1
	N2 PortPoEOverviewType = 2
	N3 PortPoEOverviewType = 3
	N4 PortPoEOverviewType = 4
)

// Valid indicates whether the value is a known member of the PortPoEOverviewType enum.
func (e PortPoEOverviewType) Valid() bool {
	switch e {
	case N1:
		return true
	case N2:
		return true
	case N3:
		return true
	case N4:
		return true
	default:
		return false
	}
}

// Defines values for PortOverviewConnector.
const (
	QSFP28  PortOverviewConnector = "QSFP28"
	RJ45    PortOverviewConnector = "RJ45"
	SFP     PortOverviewConnector = "SFP"
	SFP28   PortOverviewConnector = "SFP28"
	SFPPLUS PortOverviewConnector = "SFPPLUS"
)

// Valid indicates whether the value is a known member of the PortOverviewConnector enum.
func (e PortOverviewConnector) Valid() bool {
	switch e {
	case QSFP28:
		return true
	case RJ45:
		return true
	case SFP:
		return true
	case SFP28:
		return true
	case SFPPLUS:
		return true
	default:
		return false
	}
}

// Defines values for PortOverviewState.
const (
	PortOverviewStateDOWN    PortOverviewState = "DOWN"
	PortOverviewStateUNKNOWN PortOverviewState = "UNKNOWN"
	PortOverviewStateUP      PortOverviewState = "UP"
)

// Valid indicates whether the value is a known member of the PortOverviewState enum.
func (e PortOverviewState) Valid() bool {
	switch e {
	case PortOverviewStateDOWN:
		return true
	case PortOverviewStateUNKNOWN:
		return true
	case PortOverviewStateUP:
		return true
	default:
		return false
	}
}

// Defines values for WirelessRadioOverviewFrequencyGHz.
const (
	WirelessRadioOverviewFrequencyGHzN24 WirelessRadioOverviewFrequencyGHz = 2.4
	WirelessRadioOverviewFrequencyGHzN5  WirelessRadioOverviewFrequencyGHz = 5
	WirelessRadioOverviewFrequencyGHzN6  WirelessRadioOverviewFrequencyGHz = 6
	WirelessRadioOverviewFrequencyGHzN60 WirelessRadioOverviewFrequencyGHz = 60
)

// Valid indicates whether the value is a known member of the WirelessRadioOverviewFrequencyGHz enum.
func (e WirelessRadioOverviewFrequencyGHz) Valid() bool {
	switch e {
	case WirelessRadioOverviewFrequencyGHzN24:
		return true
	case WirelessRadioOverviewFrequencyGHzN5:
		return true
	case WirelessRadioOverviewFrequencyGHzN6:
		return true
	case WirelessRadioOverviewFrequencyGHzN60:
		return true
	default:
		return false
	}
}

// Defines values for WirelessRadioOverviewWlanStandard.
const (
	N80211a  WirelessRadioOverviewWlanStandard = "802.11a"
	N80211ac WirelessRadioOverviewWlanStandard = "802.11ac"
	N80211ax WirelessRadioOverviewWlanStandard = "802.11ax"
	N80211b  WirelessRadioOverviewWlanStandard = "802.11b"
	N80211be WirelessRadioOverviewWlanStandard = "802.11be"
	N80211g  WirelessRadioOverviewWlanStandard = "802.11g"
	N80211n  WirelessRadioOverviewWlanStandard = "802.11n"
)

// Valid indicates whether the value is a known member of the WirelessRadioOverviewWlanStandard enum.
func (e WirelessRadioOverviewWlanStandard) Valid() bool {
	switch e {
	case N80211a:
		return true
	case N80211ac:
		return true
	case N80211ax:
		return true
	case N80211b:
		return true
	case N80211be:
		return true
	case N80211g:
		return true
	case N80211n:
		return true
	default:
		return false
	}
}

// ACLRule defines model for ACL rule.
type ACLRule struct {
	// Action ACL rule action
	Action ACLRuleAction `json:"action"`

	// Description ACL rule description
	Description *string `json:"description,omitempty"`

	// DestinationFilter Traffic destination filter
	DestinationFilter     interface{}          `json:"destinationFilter,omitempty"`
	Enabled               bool                 `json:"enabled"`
	EnforcingDeviceFilter *ACLRuleDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	Id                    openapi_types.UUID   `json:"id"`

	// Index ACL rule index. Lower index has higher priority
	Index    int32                              `json:"index"`
	Metadata UserDefinedOrDerivedEntityMetadata `json:"metadata"`

	// Name ACL rule name
	Name string `json:"name"`

	// SourceFilter Traffic source filter
	SourceFilter interface{} `json:"sourceFilter,omitempty"`
	Type         string      `json:"type"`
}

// ACLRuleAction ACL rule action
type ACLRuleAction string

// ACLRuleDeviceFilter defines model for ACL rule device filter.
type ACLRuleDeviceFilter struct {
	Type string `json:"type"`
}

// ACLRuleOrdering defines model for ACL rule ordering.
type ACLRuleOrdering struct {
	OrderedAclRuleIds []openapi_types.UUID `json:"orderedAclRuleIds"`
}

// ACLRuleUpdate defines model for ACL rule update.
type ACLRuleUpdate struct {
	// Action ACL rule action
	Action ACLRuleUpdateAction `json:"action"`

	// Description ACL rule description
	Description *string `json:"description,omitempty"`

	// DestinationFilter Traffic destination filter
	DestinationFilter     interface{}          `json:"destinationFilter,omitempty"`
	Enabled               bool                 `json:"enabled"`
	EnforcingDeviceFilter *ACLRuleDeviceFilter `json:"enforcingDeviceFilter,omitempty"`

	// Index ACL rule index. This property is deprecated and has no effect. Use the dedicated ACL rule reordering endpoint.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Index *int32 `json:"index,omitempty"`

	// Name ACL rule name
	Name string `json:"name"`

	// SourceFilter Traffic source filter
	SourceFilter interface{} `json:"sourceFilter,omitempty"`
	Type         string      `json:"type"`
}

// ACLRuleUpdateAction ACL rule action
type ACLRuleUpdateAction string

// ACLRuleObject defines model for ACL ruleObject.
type ACLRuleObject struct {
	// Action ACL rule action
	Action ACLRuleObjectAction `json:"action"`

	// Description ACL rule description
	Description *string `json:"description,omitempty"`

	// DestinationFilter Traffic destination filter
	DestinationFilter     interface{}          `json:"destinationFilter,omitempty"`
	Enabled               bool                 `json:"enabled"`
	EnforcingDeviceFilter *ACLRuleDeviceFilter `json:"enforcingDeviceFilter,omitempty"`
	Id                    openapi_types.UUID   `json:"id"`

	// Index ACL rule index. Lower index has higher priority
	Index    int32                              `json:"index"`
	Metadata UserDefinedOrDerivedEntityMetadata `json:"metadata"`

	// Name ACL rule name
	Name string `json:"name"`

	// SourceFilter Traffic source filter
	SourceFilter interface{} `json:"sourceFilter,omitempty"`
	Type         string      `json:"type"`
}

// ACLRuleObjectAction ACL rule action
type ACLRuleObjectAction string

// AccessPointFeatureOverview defines model for Access point feature overview.
type AccessPointFeatureOverview = interface{}

// AdoptedDeviceDetails defines model for Adopted device details.
type AdoptedDeviceDetails struct {
	AdoptedAt         *time.Time                `json:"adoptedAt,omitempty"`
	ConfigurationId   string                    `json:"configurationId"`
	Features          DeviceFeatures            `json:"features"`
	FirmwareUpdatable bool                      `json:"firmwareUpdatable"`
	FirmwareVersion   *string                   `json:"firmwareVersion,omitempty"`
	Id                openapi_types.UUID        `json:"id"`
	Interfaces        DevicePhysicalInterfaces  `json:"interfaces"`
	IpAddress         string                    `json:"ipAddress"`
	MacAddress        string                    `json:"macAddress"`
	Model             string                    `json:"model"`
	Name              string                    `json:"name"`
	ProvisionedAt     *time.Time                `json:"provisionedAt,omitempty"`
	State             AdoptedDeviceDetailsState `json:"state"`
	Supported         bool                      `json:"supported"`

	// Uplink Uplink interface is device's connection to the parent device in the network topology
	Uplink *DeviceUplinkInterfaceOverview `json:"uplink,omitempty"`
}

// AdoptedDeviceDetailsState defines model for AdoptedDeviceDetails.State.
type AdoptedDeviceDetailsState string

// AdoptedDeviceOverview defines model for Adopted device overview.
type AdoptedDeviceOverview struct {
	Features          []AdoptedDeviceOverviewFeatures   `json:"features"`
	FirmwareUpdatable bool                              `json:"firmwareUpdatable"`
	FirmwareVersion   *string                           `json:"firmwareVersion,omitempty"`
	Id                openapi_types.UUID                `json:"id"`
	Interfaces        []AdoptedDeviceOverviewInterfaces `json:"interfaces"`
	IpAddress         string                            `json:"ipAddress"`
	MacAddress        string                            `json:"macAddress"`
	Model             string                            `json:"model"`
	Name              string                            `json:"name"`
	State             AdoptedDeviceOverviewState        `json:"state"`
	Supported         bool                              `json:"supported"`
}

// AdoptedDeviceOverviewFeatures defines model for AdoptedDeviceOverview.Features.
type AdoptedDeviceOverviewFeatures string

// AdoptedDeviceOverviewInterfaces defines model for AdoptedDeviceOverview.Interfaces.
type AdoptedDeviceOverviewInterfaces string

// AdoptedDeviceOverviewState defines model for AdoptedDeviceOverview.State.
type AdoptedDeviceOverviewState string

// AdoptedDeviceOverviewPage defines model for Adopted device overview page.
type AdoptedDeviceOverviewPage struct {
	Count      int32                   `json:"count"`
	Data       []AdoptedDeviceOverview `json:"data"`
	Limit      int32                   `json:"limit"`
	Offset     int64                   `json:"offset"`
	TotalCount int64                   `json:"totalCount"`
}

// ApplicationInfo defines model for Application info.
type ApplicationInfo struct {
	ApplicationVersion string `json:"applicationVersion"`
}

// BlackoutScheduleConfigurationPerDay defines model for Blackout schedule configuration per day.
type BlackoutScheduleConfigurationPerDay struct {
	Day  BlackoutScheduleConfigurationPerDayDay `json:"day"`
	Type string                                 `json:"type"`
}

// BlackoutScheduleConfigurationPerDayDay defines model for BlackoutScheduleConfigurationPerDay.Day.
type BlackoutScheduleConfigurationPerDayDay string

// BroadcastingDeviceFilter defines model for Broadcasting device filter.
type BroadcastingDeviceFilter struct {
	Type string `json:"type"`
}

// ClientAccessOverview defines model for Client access overview.
type ClientAccessOverview = interface{}

// ClientActionRequest defines model for Client action request.
type ClientActionRequest struct {
	Action string `json:"action"`
}

// ClientActionResponse defines model for Client action response.
type ClientActionResponse struct {
	Action string `json:"action"`
}

// ClientDetails defines model for Client details.
type ClientDetails struct {
	Access      interface{}        `json:"access"`
	ConnectedAt *time.Time         `json:"connectedAt,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	IpAddress   *string            `json:"ipAddress,omitempty"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
}

// ClientOverview defines model for Client overview.
type ClientOverview struct {
	Access      ClientAccessOverview `json:"access"`
	ConnectedAt *time.Time           `json:"connectedAt,omitempty"`
	Id          openapi_types.UUID   `json:"id"`
	IpAddress   *string              `json:"ipAddress,omitempty"`
	Name        string               `json:"name"`
	Type        string               `json:"type"`
}

// ClientOverviewPage defines model for Client overview page.
type ClientOverviewPage struct {
	Count      int32            `json:"count"`
	Data       []ClientOverview `json:"data"`
	Limit      int32            `json:"limit"`
	Offset     int64            `json:"offset"`
	TotalCount int64            `json:"totalCount"`
}

// CountryDefinition defines model for Country Definition.
type CountryDefinition struct {
	// Code The country code in ISO 3166-1 alpha-2 format.
	Code string `json:"code"`

	// Name The country name.
	Name string `json:"name"`
}

// CountryDefinitionPage defines model for Country definition page.
type CountryDefinitionPage struct {
	Count      int32               `json:"count"`
	Data       []CountryDefinition `json:"data"`
	Limit      int32               `json:"limit"`
	Offset     int64               `json:"offset"`
	TotalCount int64               `json:"totalCount"`
}

// CreateOrUpdateDNSPolicy defines model for Create or update DNS policy.
type CreateOrUpdateDNSPolicy struct {
	Enabled bool   `json:"enabled"`
	Type    string `json:"type"`
}

// CreateOrUpdateNetwork defines model for Create or update Network.
type CreateOrUpdateNetwork struct {
	// DhcpGuarding Details about DHCP Guarding settings for this Network.
	DhcpGuarding *NetworkDHCPGuarding `json:"dhcpGuarding,omitempty"`
	Enabled      bool                 `json:"enabled"`
	Management   string               `json:"management"`
	Name         string               `json:"name"`

	// VlanId VLAN ID. Must be 1 for the default network and >= 2 for additional networks.
	VlanId int32 `json:"vlanId"`
}

// CreateOrUpdateFirewallPolicy defines model for Create or update firewall policy.
type CreateOrUpdateFirewallPolicy struct {
	// Action Defines action for matched traffic.
	Action FirewallPolicyAction `json:"action"`

	// ConnectionStateFilter Match on firewall connection state. If null, matches all connection states.
	ConnectionStateFilter *[]CreateOrUpdateFirewallPolicyConnectionStateFilter `json:"connectionStateFilter,omitempty"`
	Description           *string                                              `json:"description,omitempty"`
	Destination           FirewallPolicyDestination                            `json:"destination"`
	Enabled               bool                                                 `json:"enabled"`

	// IpProtocolScope Defines rules for matching by IP version and protocol.
	IpProtocolScope FirewallPolicyIPProtocolScope `json:"ipProtocolScope"`

	// IpsecFilter Match on traffic encrypted, or not encrypted by IPsec. If null, matches all traffic.
	IpsecFilter *CreateOrUpdateFirewallPolicyIpsecFilter `json:"ipsecFilter,omitempty"`

	// LoggingEnabled Generate syslog entries when traffic is matched. Such entries are sent to a remote syslog server.
	LoggingEnabled bool   `json:"loggingEnabled"`
	Name           string `json:"name"`

	// Schedule Defines date and time when the entity is active. If null, the entity is always active.
	Schedule *FirewallSchedule    `json:"schedule,omitempty"`
	Source   FirewallPolicySource `json:"source"`
}

// CreateOrUpdateFirewallPolicyConnectionStateFilter defines model for CreateOrUpdateFirewallPolicy.ConnectionStateFilter.
type CreateOrUpdateFirewallPolicyConnectionStateFilter string

// CreateOrUpdateFirewallPolicyIpsecFilter Match on traffic encrypted, or not encrypted by IPsec. If null, matches all traffic.
type CreateOrUpdateFirewallPolicyIpsecFilter string

// CreateOrUpdateFirewallZone defines model for Create or update firewall zone.
type CreateOrUpdateFirewallZone struct {
	// Name Name of a firewall zone
	Name string `json:"name"`

	// NetworkIds List of Network IDs
	NetworkIds []openapi_types.UUID `json:"networkIds"`
}

// CreateOrUpdateTrafficMatchingList defines model for Create or update traffic matching list.
type CreateOrUpdateTrafficMatchingList struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// DNSPolicy defines model for DNS policy.
type DNSPolicy struct {
	Domain   *string                   `json:"domain,omitempty"`
	Enabled  bool                      `json:"enabled"`
	Id       openapi_types.UUID        `json:"id"`
	Metadata UserDefinedEntityMetadata `json:"metadata"`
	Type     string                    `json:"type"`
}

// DPIApplication defines model for DPI application.
type DPIApplication struct {
	Id   int32  `json:"id"`
	Name string `json:"name"`
}

// DPIApplicationPage defines model for DPI application page.
type DPIApplicationPage struct {
	Count      int32            `json:"count"`
	Data       []DPIApplication `json:"data"`
	Limit      int32            `json:"limit"`
	Offset     int64            `json:"offset"`
	TotalCount int64            `json:"totalCount"`
}

// DPICategory defines model for DPI category.
type DPICategory struct {
	Id   int32  `json:"id"`
	Name string `json:"name"`
}

// DPICategoryPage defines model for DPI category page.
type DPICategoryPage struct {
	Count      int32         `json:"count"`
	Data       []DPICategory `json:"data"`
	Limit      int32         `json:"limit"`
	Offset     int64         `json:"offset"`
	TotalCount int64         `json:"totalCount"`
}

// DeviceActionRequest defines model for Device action request.
type DeviceActionRequest struct {
	Action string `json:"action"`
}

// DeviceFeatures defines model for Device features.
type DeviceFeatures struct {
	AccessPoint *AccessPointFeatureOverview `json:"accessPoint,omitempty"`
	Switching   *SwitchFeatureOverview      `json:"switching,omitempty"`
}

// DevicePendingAdoption defines model for Device pending adoption.
type DevicePendingAdoption struct {
	AdoptionTargetSiteIds []openapi_types.UUID            `json:"adoptionTargetSiteIds"`
	Features              []DevicePendingAdoptionFeatures `json:"features"`
	FirmwareUpdatable     bool                            `json:"firmwareUpdatable"`
	FirmwareVersion       *string                         `json:"firmwareVersion,omitempty"`
	IpAddress             string                          `json:"ipAddress"`
	MacAddress            string                          `json:"macAddress"`
	Model                 string                          `json:"model"`
	State                 DevicePendingAdoptionState      `json:"state"`
	Supported             bool                            `json:"supported"`
}

// DevicePendingAdoptionFeatures defines model for DevicePendingAdoption.Features.
type DevicePendingAdoptionFeatures string

// DevicePendingAdoptionState defines model for DevicePendingAdoption.State.
type DevicePendingAdoptionState string

// DevicePendingAdoptionPage defines model for Device pending adoption page.
type DevicePendingAdoptionPage struct {
	Count      int32                   `json:"count"`
	Data       []DevicePendingAdoption `json:"data"`
	Limit      int32                   `json:"limit"`
	Offset     int64                   `json:"offset"`
	TotalCount int64                   `json:"totalCount"`
}

// DevicePhysicalInterfaces defines model for Device physical interfaces.
type DevicePhysicalInterfaces struct {
	Ports  *[]PortOverview          `json:"ports,omitempty"`
	Radios *[]WirelessRadioOverview `json:"radios,omitempty"`
}

// DeviceTag defines model for Device tag.
type DeviceTag struct {
	DeviceIds []openapi_types.UUID             `json:"deviceIds"`
	Id        openapi_types.UUID               `json:"id"`
	Metadata  UserOrOrchestratedEntityMetadata `json:"metadata"`
	Name      string                           `json:"name"`
}

// DeviceUplinkInterfaceOverview Uplink interface is device's connection to the parent device in the network topology
type DeviceUplinkInterfaceOverview struct {
	DeviceId openapi_types.UUID `json:"deviceId"`
}

// EntityMetadata defines model for Entity metadata.
type EntityMetadata struct {
	Origin string `json:"origin"`
}

// FilterExpression defines model for FilterExpression.
type FilterExpression = interface{}

// FirewallPolicy defines model for Firewall policy.
type FirewallPolicy struct {
	// Action Defines action for matched traffic.
	Action FirewallPolicyAction `json:"action"`

	// ConnectionStateFilter Match on firewall connection state. If null, matches all connection states.
	ConnectionStateFilter *[]FirewallPolicyConnectionStateFilter `json:"connectionStateFilter,omitempty"`
	Description           *string                                `json:"description,omitempty"`
	Destination           FirewallPolicyDestination              `json:"destination"`
	Enabled               bool                                   `json:"enabled"`
	Id                    openapi_types.UUID                     `json:"id"`
	Index                 int32                                  `json:"index"`

	// IpProtocolScope Defines rules for matching by IP version and protocol.
	IpProtocolScope FirewallPolicyIPProtocolScope `json:"ipProtocolScope"`

	// IpsecFilter Match on traffic encrypted, or not encrypted by IPsec. If null, matches all traffic.
	IpsecFilter *FirewallPolicyIpsecFilter `json:"ipsecFilter,omitempty"`

	// LoggingEnabled Generate syslog entries when traffic is matched. Such entries are sent to a remote syslog server.
	LoggingEnabled bool                                       `json:"loggingEnabled"`
	Metadata       UserOrSystemDefinedOrDerivedEntityMetadata `json:"metadata"`
	Name           string                                     `json:"name"`

	// Schedule Defines date and time when the entity is active. If null, the entity is always active.
	Schedule *FirewallSchedule    `json:"schedule,omitempty"`
	Source   FirewallPolicySource `json:"source"`
}

// FirewallPolicyConnectionStateFilter defines model for FirewallPolicy.ConnectionStateFilter.
type FirewallPolicyConnectionStateFilter string

// FirewallPolicyIpsecFilter Match on traffic encrypted, or not encrypted by IPsec. If null, matches all traffic.
type FirewallPolicyIpsecFilter string

// FirewallPolicyIPProtocolScope Defines rules for matching by IP version and protocol.
type FirewallPolicyIPProtocolScope struct {
	IpVersion string `json:"ipVersion"`
}

// FirewallPolicyAction Defines action for matched traffic.
type FirewallPolicyAction struct {
	Type string `json:"type"`
}

// FirewallPolicyDestination defines model for Firewall policy destination.
type FirewallPolicyDestination struct {
	TrafficFilter *FirewallPolicyDestinationTrafficFilter `json:"trafficFilter,omitempty"`

	// ZoneId ID of the firewall zone to which the matched traffic is destined.
	ZoneId openapi_types.UUID `json:"zoneId"`
}

// FirewallPolicyDestinationTrafficFilter defines model for Firewall policy destination traffic filter.
type FirewallPolicyDestinationTrafficFilter struct {
	Type string `json:"type"`
}

// FirewallPolicyPage defines model for Firewall policy page.
type FirewallPolicyPage struct {
	Count      int32            `json:"count"`
	Data       []FirewallPolicy `json:"data"`
	Limit      int32            `json:"limit"`
	Offset     int64            `json:"offset"`
	TotalCount int64            `json:"totalCount"`
}

// FirewallPolicySource defines model for Firewall policy source.
type FirewallPolicySource struct {
	TrafficFilter *FirewallPolicySourceTrafficFilter `json:"trafficFilter,omitempty"`

	// ZoneId ID of the firewall zone from which the matched traffic originates.
	ZoneId openapi_types.UUID `json:"zoneId"`
}

// FirewallPolicySourceTrafficFilter defines model for Firewall policy source traffic filter.
type FirewallPolicySourceTrafficFilter struct {
	Type string `json:"type"`
}

// FirewallSchedule Defines date and time when the entity is active. If null, the entity is always active.
type FirewallSchedule struct {
	Mode string `json:"mode"`
}

// FirewallZone defines model for Firewall zone.
type FirewallZone struct {
	Id       openapi_types.UUID                `json:"id"`
	Metadata UserOrSystemDefinedEntityMetadata `json:"metadata"`

	// Name Name of a firewall zone
	Name string `json:"name"`

	// NetworkIds List of Network IDs
	NetworkIds []openapi_types.UUID `json:"networkIds"`
}

// FirewallZonesPage defines model for Firewall zones page.
type FirewallZonesPage struct {
	Count      int32          `json:"count"`
	Data       []FirewallZone `json:"data"`
	Limit      int32          `json:"limit"`
	Offset     int64          `json:"offset"`
	TotalCount int64          `json:"totalCount"`
}

// HotspotVoucherCreationRequest defines model for Hotspot voucher creation request.
type HotspotVoucherCreationRequest struct {
	// AuthorizedGuestLimit (Optional) limit for how many different guests can use the same voucher to authorize network access
	AuthorizedGuestLimit *int64 `json:"authorizedGuestLimit,omitempty"`

	// Count Number of vouchers to generate
	Count *int32 `json:"count,omitempty"`

	// DataUsageLimitMBytes (Optional) data usage limit in megabytes
	DataUsageLimitMBytes *int64 `json:"dataUsageLimitMBytes,omitempty"`

	// Name Voucher note, duplicated across all generated vouchers
	Name string `json:"name"`

	// RxRateLimitKbps (Optional) download rate limit in kilobits per second
	RxRateLimitKbps *int64 `json:"rxRateLimitKbps,omitempty"`

	// TimeLimitMinutes How long (in minutes) the voucher will provide access to the network since authorization of the first guest.
	// Subsequently connected guests, if allowed, will share the same expiration time.
	TimeLimitMinutes int64 `json:"timeLimitMinutes"`

	// TxRateLimitKbps (Optional) upload rate limit in kilobits per second
	TxRateLimitKbps *int64 `json:"txRateLimitKbps,omitempty"`
}

// HotspotVoucherDetailPage defines model for Hotspot voucher detail page.
type HotspotVoucherDetailPage struct {
	Count      int32                   `json:"count"`
	Data       []HotspotVoucherDetails `json:"data"`
	Limit      int32                   `json:"limit"`
	Offset     int64                   `json:"offset"`
	TotalCount int64                   `json:"totalCount"`
}

// HotspotVoucherDetails defines model for Hotspot voucher details.
type HotspotVoucherDetails struct {
	// ActivatedAt (Optional) timestamp when the voucher has been activated (authorization time of the first guest)
	ActivatedAt *time.Time `json:"activatedAt,omitempty"`

	// AuthorizedGuestCount For how many guests the voucher has been used to authorize network access
	AuthorizedGuestCount int64 `json:"authorizedGuestCount"`

	// AuthorizedGuestLimit (Optional) limit for how many different guests can use the same voucher to authorize network access
	AuthorizedGuestLimit *int64 `json:"authorizedGuestLimit,omitempty"`

	// Code Secret code to active the voucher using the Hotspot portal
	Code      string    `json:"code"`
	CreatedAt time.Time `json:"createdAt"`

	// DataUsageLimitMBytes (Optional) data usage limit in megabytes
	DataUsageLimitMBytes *int64 `json:"dataUsageLimitMBytes,omitempty"`

	// Expired Whether the voucher has been expired and can no longer be used to authorize network access
	Expired bool `json:"expired"`

	// ExpiresAt (Optional) timestamp when the voucher will become expired. All guests using the voucher will be unauthorized from network access
	ExpiresAt *time.Time         `json:"expiresAt,omitempty"`
	Id        openapi_types.UUID `json:"id"`

	// Name Voucher note, may contain duplicate values across multiple vouchers
	Name string `json:"name"`

	// RxRateLimitKbps (Optional) download rate limit in kilobits per second
	RxRateLimitKbps *int64 `json:"rxRateLimitKbps,omitempty"`

	// TimeLimitMinutes How long (in minutes) the voucher will provide access to the network since authorization of the first guest.
	// Subsequently connected guests, if allowed, will share the same expiration time.
	TimeLimitMinutes int64 `json:"timeLimitMinutes"`

	// TxRateLimitKbps (Optional) upload rate limit in kilobits per second
	TxRateLimitKbps *int64 `json:"txRateLimitKbps,omitempty"`
}

// IntegrationBlackoutScheduleConfiguration defines model for Integration blackout schedule configuration.
type IntegrationBlackoutScheduleConfiguration struct {
	Days []BlackoutScheduleConfigurationPerDay `json:"days"`
}

// IntegrationAclRulePageDto defines model for IntegrationAclRulePageDto.
type IntegrationAclRulePageDto struct {
	Count      int32           `json:"count"`
	Data       []ACLRuleObject `json:"data"`
	Limit      int32           `json:"limit"`
	Offset     int64           `json:"offset"`
	TotalCount int64           `json:"totalCount"`
}

// IntegrationDeviceAdoptionRequestDto defines model for IntegrationDeviceAdoptionRequestDto.
type IntegrationDeviceAdoptionRequestDto struct {
	IgnoreDeviceLimit bool   `json:"ignoreDeviceLimit"`
	MacAddress        string `json:"macAddress"`
}

// IntegrationDeviceTagPageDto defines model for IntegrationDeviceTagPageDto.
type IntegrationDeviceTagPageDto struct {
	Count      int32       `json:"count"`
	Data       []DeviceTag `json:"data"`
	Limit      int32       `json:"limit"`
	Offset     int64       `json:"offset"`
	TotalCount int64       `json:"totalCount"`
}

// IntegrationDnsPolicyPageDto defines model for IntegrationDnsPolicyPageDto.
type IntegrationDnsPolicyPageDto struct {
	Count      int32       `json:"count"`
	Data       []DNSPolicy `json:"data"`
	Limit      int32       `json:"limit"`
	Offset     int64       `json:"offset"`
	TotalCount int64       `json:"totalCount"`
}

// IntegrationFirewallPolicyOrderingDto defines model for IntegrationFirewallPolicyOrderingDto.
type IntegrationFirewallPolicyOrderingDto struct {
	OrderedFirewallPolicyIds OrderedFirewallPolicyIDs `json:"orderedFirewallPolicyIds"`
}

// IntegrationSiteToSiteVpnTunnelOverviewPageDto defines model for IntegrationSiteToSiteVpnTunnelOverviewPageDto.
type IntegrationSiteToSiteVpnTunnelOverviewPageDto struct {
	Count      int32                         `json:"count"`
	Data       []SiteToSiteVPNTunnelOverview `json:"data"`
	Limit      int32                         `json:"limit"`
	Offset     int64                         `json:"offset"`
	TotalCount int64                         `json:"totalCount"`
}

// IntegrationVoucherCreationResultDto defines model for IntegrationVoucherCreationResultDto.
type IntegrationVoucherCreationResultDto struct {
	Vouchers *[]HotspotVoucherDetails `json:"vouchers,omitempty"`
}

// IntegrationVpnServerOverviewPageDto defines model for IntegrationVpnServerOverviewPageDto.
type IntegrationVpnServerOverviewPageDto struct {
	Count      int32               `json:"count"`
	Data       []VPNServerOverview `json:"data"`
	Limit      int32               `json:"limit"`
	Offset     int64               `json:"offset"`
	TotalCount int64               `json:"totalCount"`
}

// IntegrationWifiBasicDataRateConfigurationDto defines model for IntegrationWifiBasicDataRateConfigurationDto.
type IntegrationWifiBasicDataRateConfigurationDto struct {
	N24 IntegrationWifiBasicDataRateConfigurationDto24 `json:"2.4"`
	N5  IntegrationWifiBasicDataRateConfigurationDto5  `json:"5"`
}

// IntegrationWifiBasicDataRateConfigurationDto24 defines model for IntegrationWifiBasicDataRateConfigurationDto.24.
type IntegrationWifiBasicDataRateConfigurationDto24 int32

// IntegrationWifiBasicDataRateConfigurationDto5 defines model for IntegrationWifiBasicDataRateConfigurationDto.5.
type IntegrationWifiBasicDataRateConfigurationDto5 int32

// IntegrationWifiBroadcastPageDto defines model for IntegrationWifiBroadcastPageDto.
type IntegrationWifiBroadcastPageDto struct {
	Count      int32                   `json:"count"`
	Data       []WifiBroadcastOverview `json:"data"`
	Limit      int32                   `json:"limit"`
	Offset     int64                   `json:"offset"`
	TotalCount int64                   `json:"totalCount"`
}

// IntegrationWifiClientFilteringPolicyDto defines model for IntegrationWifiClientFilteringPolicyDto.
type IntegrationWifiClientFilteringPolicyDto struct {
	Action           IntegrationWifiClientFilteringPolicyDtoAction `json:"action"`
	MacAddressFilter []string                                      `json:"macAddressFilter"`
}

// IntegrationWifiClientFilteringPolicyDtoAction defines model for IntegrationWifiClientFilteringPolicyDto.Action.
type IntegrationWifiClientFilteringPolicyDtoAction string

// LatestStatisticsForADevice defines model for Latest statistics for a device.
type LatestStatisticsForADevice struct {
	CpuUtilizationPct    *float64                                   `json:"cpuUtilizationPct,omitempty"`
	Interfaces           LatestStatisticsForDeviceInterfaces        `json:"interfaces"`
	LastHeartbeatAt      *time.Time                                 `json:"lastHeartbeatAt,omitempty"`
	LoadAverage15Min     *float64                                   `json:"loadAverage15Min,omitempty"`
	LoadAverage1Min      *float64                                   `json:"loadAverage1Min,omitempty"`
	LoadAverage5Min      *float64                                   `json:"loadAverage5Min,omitempty"`
	MemoryUtilizationPct *float64                                   `json:"memoryUtilizationPct,omitempty"`
	NextHeartbeatAt      *time.Time                                 `json:"nextHeartbeatAt,omitempty"`
	Uplink               *LatestStatisticsForADeviceUplinkInterface `json:"uplink,omitempty"`
	UptimeSec            *int64                                     `json:"uptimeSec,omitempty"`
}

// LatestStatisticsForADeviceUplinkInterface defines model for Latest statistics for a device uplink interface.
type LatestStatisticsForADeviceUplinkInterface struct {
	RxRateBps *int64 `json:"rxRateBps,omitempty"`
	TxRateBps *int64 `json:"txRateBps,omitempty"`
}

// LatestStatisticsForDeviceInterfaces defines model for Latest statistics for device interfaces.
type LatestStatisticsForDeviceInterfaces struct {
	Radios *[]LatestStatisticsForWirelessRadio `json:"radios,omitempty"`
}

// LatestStatisticsForWirelessRadio defines model for Latest statistics for wireless radio.
type LatestStatisticsForWirelessRadio struct {
	FrequencyGHz LatestStatisticsForWirelessRadioFrequencyGHz `json:"frequencyGHz"`
	TxRetriesPct *float64                                     `json:"txRetriesPct,omitempty"`
}

// LatestStatisticsForWirelessRadioFrequencyGHz defines model for LatestStatisticsForWirelessRadio.FrequencyGHz.
type LatestStatisticsForWirelessRadioFrequencyGHz float32

// MulticastFilteringPolicy defines model for Multicast filtering policy.
type MulticastFilteringPolicy struct {
	Action string `json:"action"`
}

// NetworkDHCPGuarding Details about DHCP Guarding settings for this Network.
type NetworkDHCPGuarding struct {
	// TrustedDhcpServerIpAddresses List of trusted DHCP server IP addresses.
	TrustedDhcpServerIpAddresses []string `json:"trustedDhcpServerIpAddresses"`
}

// NetworkDetails defines model for Network details.
type NetworkDetails struct {
	Default bool `json:"default"`

	// DhcpGuarding Details about DHCP Guarding settings for this Network.
	DhcpGuarding *NetworkDHCPGuarding                            `json:"dhcpGuarding,omitempty"`
	Enabled      bool                                            `json:"enabled"`
	Id           openapi_types.UUID                              `json:"id"`
	Management   string                                          `json:"management"`
	Metadata     UserOrSystemDefinedOrOrchestratedEntityMetadata `json:"metadata"`
	Name         string                                          `json:"name"`

	// VlanId VLAN ID. Must be 1 for the default network and >= 2 for additional networks.
	VlanId int32 `json:"vlanId"`
}

// NetworkOverview defines model for Network overview.
type NetworkOverview struct {
	Default    bool                                            `json:"default"`
	Enabled    bool                                            `json:"enabled"`
	Id         openapi_types.UUID                              `json:"id"`
	Management string                                          `json:"management"`
	Metadata   UserOrSystemDefinedOrOrchestratedEntityMetadata `json:"metadata"`
	Name       string                                          `json:"name"`

	// VlanId VLAN ID. Must be 1 for the default network and >= 2 for additional networks.
	VlanId int32 `json:"vlanId"`
}

// NetworkOverviewPage defines model for Network overview page.
type NetworkOverviewPage struct {
	Count      int32             `json:"count"`
	Data       []NetworkOverview `json:"data"`
	Limit      int32             `json:"limit"`
	Offset     int64             `json:"offset"`
	TotalCount int64             `json:"totalCount"`
}

// NetworkReferenceDetail defines model for Network reference detail.
type NetworkReferenceDetail struct {
	ReferenceId openapi_types.UUID `json:"referenceId"`
}

// NetworkReferenceResource defines model for Network reference resource.
type NetworkReferenceResource struct {
	// ReferenceCount Number of references of this type
	ReferenceCount int32 `json:"referenceCount"`

	// References List of references, present only if resourceType has API model defined
	References   *[]NetworkReferenceDetail            `json:"references,omitempty"`
	ResourceType NetworkReferenceResourceResourceType `json:"resourceType"`
}

// NetworkReferenceResourceResourceType defines model for NetworkReferenceResource.ResourceType.
type NetworkReferenceResourceResourceType string

// NetworkReferences defines model for Network references.
type NetworkReferences struct {
	// ReferenceResources List of network reference resources
	ReferenceResources []NetworkReferenceResource `json:"referenceResources"`
}

// OrderedFirewallPolicyIDs defines model for Ordered firewall policy IDs.
type OrderedFirewallPolicyIDs struct {
	AfterSystemDefined  []openapi_types.UUID `json:"afterSystemDefined"`
	BeforeSystemDefined []openapi_types.UUID `json:"beforeSystemDefined"`
}

// PatchFirewallPolicy defines model for Patch firewall policy.
type PatchFirewallPolicy struct {
	LoggingEnabled *bool `json:"loggingEnabled,omitempty"`
}

// PortPoEOverview defines model for Port PoE overview.
type PortPoEOverview struct {
	// Enabled Whether the PoE feature is enabled on the port
	Enabled  bool                    `json:"enabled"`
	Standard PortPoEOverviewStandard `json:"standard"`

	// State Whether the port currently supplies power to the (connected) device.
	State PortPoEOverviewState `json:"state"`
	Type  PortPoEOverviewType  `json:"type"`
}

// PortPoEOverviewStandard defines model for PortPoEOverview.Standard.
type PortPoEOverviewStandard string

// PortPoEOverviewState Whether the port currently supplies power to the (connected) device.
type PortPoEOverviewState string

// PortPoEOverviewType defines model for PortPoEOverview.Type.
type PortPoEOverviewType int32

// PortActionRequest defines model for Port action request.
type PortActionRequest struct {
	Action string `json:"action"`
}

// PortOverview defines model for Port overview.
type PortOverview struct {
	Connector    PortOverviewConnector `json:"connector"`
	Idx          int32                 `json:"idx"`
	MaxSpeedMbps int32                 `json:"maxSpeedMbps"`
	Poe          *PortPoEOverview      `json:"poe,omitempty"`
	SpeedMbps    *int32                `json:"speedMbps,omitempty"`
	State        PortOverviewState     `json:"state"`
}

// PortOverviewConnector defines model for PortOverview.Connector.
type PortOverviewConnector string

// PortOverviewState defines model for PortOverview.State.
type PortOverviewState string

// RadiusProfileOverview defines model for Radius Profile Overview.
type RadiusProfileOverview struct {
	Id       openapi_types.UUID                         `json:"id"`
	Metadata UserOrSystemDefinedOrDerivedEntityMetadata `json:"metadata"`
	Name     string                                     `json:"name"`
}

// RadiusProfileOverviewPage defines model for Radius Profile Overview Page.
type RadiusProfileOverviewPage struct {
	Count      int32                   `json:"count"`
	Data       []RadiusProfileOverview `json:"data"`
	Limit      int32                   `json:"limit"`
	Offset     int64                   `json:"offset"`
	TotalCount int64                   `json:"totalCount"`
}

// SiteOverview defines model for Site overview.
type SiteOverview struct {
	Id openapi_types.UUID `json:"id"`

	// InternalReference Internal unique name of the site used in older APIs
	InternalReference string `json:"internalReference"`
	Name              string `json:"name"`
}

// SiteOverviewPage defines model for Site overview page.
type SiteOverviewPage struct {
	Count      int32          `json:"count"`
	Data       []SiteOverview `json:"data"`
	Limit      int32          `json:"limit"`
	Offset     int64          `json:"offset"`
	TotalCount int64          `json:"totalCount"`
}

// SiteToSiteVPNTunnelMetadata defines model for Site-to-site VPN tunnel metadata.
type SiteToSiteVPNTunnelMetadata struct {
	Origin string `json:"origin"`
}

// SiteToSiteVPNTunnelOverview defines model for Site-to-site VPN tunnel overview.
type SiteToSiteVPNTunnelOverview struct {
	Id       openapi_types.UUID          `json:"id"`
	Metadata SiteToSiteVPNTunnelMetadata `json:"metadata"`
	Name     string                      `json:"name"`
	Type     string                      `json:"type"`
}

// SwitchFeatureOverview defines model for Switch feature overview.
type SwitchFeatureOverview = interface{}

// TrafficMatchingList defines model for Traffic matching list.
type TrafficMatchingList struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Type string             `json:"type"`
}

// TrafficMatchingListsPage defines model for Traffic matching lists page.
type TrafficMatchingListsPage struct {
	Count      int32                 `json:"count"`
	Data       []TrafficMatchingList `json:"data"`
	Limit      int32                 `json:"limit"`
	Offset     int64                 `json:"offset"`
	TotalCount int64                 `json:"totalCount"`
}

// UserDefinedEntityMetadata defines model for User defined entity metadata.
type UserDefinedEntityMetadata struct {
	Origin string `json:"origin"`
}

// UserDefinedOrDerivedEntityMetadata defines model for User defined or derived entity metadata.
type UserDefinedOrDerivedEntityMetadata struct {
	Origin string `json:"origin"`
}

// UserOrDerivedOrOrchestratedEntityMetadata defines model for User or derived or orchestrated entity metadata.
type UserOrDerivedOrOrchestratedEntityMetadata struct {
	Origin string `json:"origin"`
}

// UserOrOrchestratedEntityMetadata defines model for User or orchestrated entity metadata.
type UserOrOrchestratedEntityMetadata struct {
	Origin string `json:"origin"`
}

// UserOrSystemDefinedEntityMetadata defines model for User or system defined entity metadata.
type UserOrSystemDefinedEntityMetadata struct {
	Origin string `json:"origin"`
}

// UserOrSystemDefinedOrDerivedEntityMetadata defines model for User or system defined or derived entity metadata.
type UserOrSystemDefinedOrDerivedEntityMetadata struct {
	Origin string `json:"origin"`
}

// UserOrSystemDefinedOrOrchestratedEntityMetadata defines model for User or system defined or orchestrated entity metadata.
type UserOrSystemDefinedOrOrchestratedEntityMetadata struct {
	Origin string `json:"origin"`
}

// VPNServerOverview defines model for VPN server overview.
type VPNServerOverview struct {
	Enabled  bool                               `json:"enabled"`
	Id       openapi_types.UUID                 `json:"id"`
	Metadata UserDefinedOrDerivedEntityMetadata `json:"metadata"`
	Name     string                             `json:"name"`
	Type     string                             `json:"type"`
}

// VoucherDeletionResults defines model for Voucher deletion results.
type VoucherDeletionResults struct {
	VouchersDeleted *int64 `json:"vouchersDeleted,omitempty"`
}

// WANOverview defines model for WAN overview.
type WANOverview struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// WANOverviewPage defines model for WAN overview page.
type WANOverviewPage struct {
	Count      int32         `json:"count"`
	Data       []WANOverview `json:"data"`
	Limit      int32         `json:"limit"`
	Offset     int64         `json:"offset"`
	TotalCount int64         `json:"totalCount"`
}

// WifiBroadcastCreateOrUpdate defines model for Wifi broadcast create or update.
type WifiBroadcastCreateOrUpdate struct {
	BasicDataRateKbpsByFrequencyGHz     *IntegrationWifiBasicDataRateConfigurationDto `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	BlackoutScheduleConfiguration       *IntegrationBlackoutScheduleConfiguration     `json:"blackoutScheduleConfiguration,omitempty"`
	BroadcastingDeviceFilter            *BroadcastingDeviceFilter                     `json:"broadcastingDeviceFilter,omitempty"`
	ClientFilteringPolicy               *IntegrationWifiClientFilteringPolicyDto      `json:"clientFilteringPolicy,omitempty"`
	ClientIsolationEnabled              bool                                          `json:"clientIsolationEnabled"`
	Enabled                             bool                                          `json:"enabled"`
	HideName                            bool                                          `json:"hideName"`
	MdnsProxyConfiguration              *MDNSFilteringConfiguration                   `json:"mdnsProxyConfiguration,omitempty"`
	MulticastFilteringPolicy            *MulticastFilteringPolicy                     `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                          `json:"multicastToUnicastConversionEnabled"`
	Name                                string                                        `json:"name"`
	Network                             *WifiNetworkReference                         `json:"network,omitempty"`
	SecurityConfiguration               WifiSecurityConfigurationDetailObject         `json:"securityConfiguration"`
	Type                                string                                        `json:"type"`

	// UapsdEnabled Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled bool `json:"uapsdEnabled"`
}

// WifiBroadcastDetails defines model for Wifi broadcast details.
type WifiBroadcastDetails struct {
	BasicDataRateKbpsByFrequencyGHz     *IntegrationWifiBasicDataRateConfigurationDto `json:"basicDataRateKbpsByFrequencyGHz,omitempty"`
	BlackoutScheduleConfiguration       *IntegrationBlackoutScheduleConfiguration     `json:"blackoutScheduleConfiguration,omitempty"`
	BroadcastingDeviceFilter            *BroadcastingDeviceFilter                     `json:"broadcastingDeviceFilter,omitempty"`
	ClientFilteringPolicy               *IntegrationWifiClientFilteringPolicyDto      `json:"clientFilteringPolicy,omitempty"`
	ClientIsolationEnabled              bool                                          `json:"clientIsolationEnabled"`
	Enabled                             bool                                          `json:"enabled"`
	HideName                            bool                                          `json:"hideName"`
	Id                                  openapi_types.UUID                            `json:"id"`
	MdnsProxyConfiguration              *MDNSFilteringConfiguration                   `json:"mdnsProxyConfiguration,omitempty"`
	Metadata                            UserOrDerivedOrOrchestratedEntityMetadata     `json:"metadata"`
	MulticastFilteringPolicy            *MulticastFilteringPolicy                     `json:"multicastFilteringPolicy,omitempty"`
	MulticastToUnicastConversionEnabled bool                                          `json:"multicastToUnicastConversionEnabled"`
	Name                                string                                        `json:"name"`
	Network                             *WifiNetworkReference                         `json:"network,omitempty"`
	SecurityConfiguration               WifiSecurityConfigurationDetailObject         `json:"securityConfiguration"`
	Type                                string                                        `json:"type"`

	// UapsdEnabled Indicates whether Unscheduled Automatic Power Save Delivery (U-APSD) is enabled
	UapsdEnabled bool `json:"uapsdEnabled"`
}

// WifiBroadcastOverview defines model for Wifi broadcast overview.
type WifiBroadcastOverview struct {
	BroadcastingDeviceFilter *BroadcastingDeviceFilter                 `json:"broadcastingDeviceFilter,omitempty"`
	Enabled                  bool                                      `json:"enabled"`
	Id                       openapi_types.UUID                        `json:"id"`
	Metadata                 UserOrDerivedOrOrchestratedEntityMetadata `json:"metadata"`
	Name                     string                                    `json:"name"`
	Network                  *WifiNetworkReference                     `json:"network,omitempty"`
	SecurityConfiguration    WifiSecurityConfigurationOverview         `json:"securityConfiguration"`
	Type                     string                                    `json:"type"`
}

// WifiNetworkReference defines model for Wifi network reference.
type WifiNetworkReference struct {
	Type string `json:"type"`
}

// WifiSecurityConfigurationDetailObject defines model for Wifi security configuration detailObject.
type WifiSecurityConfigurationDetailObject struct {
	RadiusConfiguration interface{} `json:"radiusConfiguration,omitempty"`
	Type                string      `json:"type"`
}

// WifiSecurityConfigurationOverview defines model for Wifi security configuration overview.
type WifiSecurityConfigurationOverview struct {
	Type string `json:"type"`
}

// WirelessRadioOverview defines model for Wireless radio overview.
type WirelessRadioOverview struct {
	Channel         *int32                            `json:"channel,omitempty"`
	ChannelWidthMHz int32                             `json:"channelWidthMHz"`
	FrequencyGHz    WirelessRadioOverviewFrequencyGHz `json:"frequencyGHz"`
	WlanStandard    WirelessRadioOverviewWlanStandard `json:"wlanStandard"`
}

// WirelessRadioOverviewFrequencyGHz defines model for WirelessRadioOverview.FrequencyGHz.
type WirelessRadioOverviewFrequencyGHz float32

// WirelessRadioOverviewWlanStandard defines model for WirelessRadioOverview.WlanStandard.
type WirelessRadioOverviewWlanStandard string

// MDNSFilteringConfiguration defines model for mDNS filtering configuration.
type MDNSFilteringConfiguration struct {
	Mode string `json:"mode"`
}

// GetCountriesParams defines parameters for GetCountries.
type GetCountriesParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetDpiApplicationsParams defines parameters for GetDpiApplications.
type GetDpiApplicationsParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetDpiApplicationCategoriesParams defines parameters for GetDpiApplicationCategories.
type GetDpiApplicationCategoriesParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetPendingDevicePageParams defines parameters for GetPendingDevicePage.
type GetPendingDevicePageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetSiteOverviewPageParams defines parameters for GetSiteOverviewPage.
type GetSiteOverviewPageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetAclRulePageParams defines parameters for GetAclRulePage.
type GetAclRulePageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetConnectedClientOverviewPageParams defines parameters for GetConnectedClientOverviewPage.
type GetConnectedClientOverviewPageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetDeviceTagPageParams defines parameters for GetDeviceTagPage.
type GetDeviceTagPageParams struct {
	Offset *int32            `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32            `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *FilterExpression `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetAdoptedDeviceOverviewPageParams defines parameters for GetAdoptedDeviceOverviewPage.
type GetAdoptedDeviceOverviewPageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetDnsPolicyPageParams defines parameters for GetDnsPolicyPage.
type GetDnsPolicyPageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetFirewallPoliciesParams defines parameters for GetFirewallPolicies.
type GetFirewallPoliciesParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetFirewallPolicyOrderingParams defines parameters for GetFirewallPolicyOrdering.
type GetFirewallPolicyOrderingParams struct {
	SourceFirewallZoneId      openapi_types.UUID `form:"sourceFirewallZoneId" json:"sourceFirewallZoneId"`
	DestinationFirewallZoneId openapi_types.UUID `form:"destinationFirewallZoneId" json:"destinationFirewallZoneId"`
}

// UpdateFirewallPolicyOrderingParams defines parameters for UpdateFirewallPolicyOrdering.
type UpdateFirewallPolicyOrderingParams struct {
	SourceFirewallZoneId      openapi_types.UUID `form:"sourceFirewallZoneId" json:"sourceFirewallZoneId"`
	DestinationFirewallZoneId openapi_types.UUID `form:"destinationFirewallZoneId" json:"destinationFirewallZoneId"`
}

// GetFirewallZonesParams defines parameters for GetFirewallZones.
type GetFirewallZonesParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// DeleteVouchersParams defines parameters for DeleteVouchers.
type DeleteVouchersParams struct {
	Filter string `form:"filter" json:"filter"`
}

// GetVouchersParams defines parameters for GetVouchers.
type GetVouchersParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetNetworksOverviewPageParams defines parameters for GetNetworksOverviewPage.
type GetNetworksOverviewPageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// DeleteNetworkParams defines parameters for DeleteNetwork.
type DeleteNetworkParams struct {
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// GetRadiusProfileOverviewPageParams defines parameters for GetRadiusProfileOverviewPage.
type GetRadiusProfileOverviewPageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetTrafficMatchingListsParams defines parameters for GetTrafficMatchingLists.
type GetTrafficMatchingListsParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetVpnServerPageParams defines parameters for GetVpnServerPage.
type GetVpnServerPageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetSiteToSiteVpnTunnelPageParams defines parameters for GetSiteToSiteVpnTunnelPage.
type GetSiteToSiteVpnTunnelPageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetWansOverviewPageParams defines parameters for GetWansOverviewPage.
type GetWansOverviewPageParams struct {
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetWifiBroadcastPageParams defines parameters for GetWifiBroadcastPage.
type GetWifiBroadcastPageParams struct {
	Offset *int32  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// DeleteWifiBroadcastParams defines parameters for DeleteWifiBroadcast.
type DeleteWifiBroadcastParams struct {
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// CreateAclRuleJSONRequestBody defines body for CreateAclRule for application/json ContentType.
type CreateAclRuleJSONRequestBody = ACLRuleUpdate

// UpdateAclRuleOrderingJSONRequestBody defines body for UpdateAclRuleOrdering for application/json ContentType.
type UpdateAclRuleOrderingJSONRequestBody = ACLRuleOrdering

// UpdateAclRuleJSONRequestBody defines body for UpdateAclRule for application/json ContentType.
type UpdateAclRuleJSONRequestBody = ACLRuleUpdate

// ExecuteConnectedClientActionJSONRequestBody defines body for ExecuteConnectedClientAction for application/json ContentType.
type ExecuteConnectedClientActionJSONRequestBody = ClientActionRequest

// AdoptDeviceJSONRequestBody defines body for AdoptDevice for application/json ContentType.
type AdoptDeviceJSONRequestBody = IntegrationDeviceAdoptionRequestDto

// ExecuteAdoptedDeviceActionJSONRequestBody defines body for ExecuteAdoptedDeviceAction for application/json ContentType.
type ExecuteAdoptedDeviceActionJSONRequestBody = DeviceActionRequest

// ExecutePortActionJSONRequestBody defines body for ExecutePortAction for application/json ContentType.
type ExecutePortActionJSONRequestBody = PortActionRequest

// CreateDnsPolicyJSONRequestBody defines body for CreateDnsPolicy for application/json ContentType.
type CreateDnsPolicyJSONRequestBody = CreateOrUpdateDNSPolicy

// UpdateDnsPolicyJSONRequestBody defines body for UpdateDnsPolicy for application/json ContentType.
type UpdateDnsPolicyJSONRequestBody = CreateOrUpdateDNSPolicy

// CreateFirewallPolicyJSONRequestBody defines body for CreateFirewallPolicy for application/json ContentType.
type CreateFirewallPolicyJSONRequestBody = CreateOrUpdateFirewallPolicy

// UpdateFirewallPolicyOrderingJSONRequestBody defines body for UpdateFirewallPolicyOrdering for application/json ContentType.
type UpdateFirewallPolicyOrderingJSONRequestBody = IntegrationFirewallPolicyOrderingDto

// PatchFirewallPolicyJSONRequestBody defines body for PatchFirewallPolicy for application/json ContentType.
type PatchFirewallPolicyJSONRequestBody = PatchFirewallPolicy

// UpdateFirewallPolicyJSONRequestBody defines body for UpdateFirewallPolicy for application/json ContentType.
type UpdateFirewallPolicyJSONRequestBody = CreateOrUpdateFirewallPolicy

// CreateFirewallZoneJSONRequestBody defines body for CreateFirewallZone for application/json ContentType.
type CreateFirewallZoneJSONRequestBody = CreateOrUpdateFirewallZone

// UpdateFirewallZoneJSONRequestBody defines body for UpdateFirewallZone for application/json ContentType.
type UpdateFirewallZoneJSONRequestBody = CreateOrUpdateFirewallZone

// CreateVouchersJSONRequestBody defines body for CreateVouchers for application/json ContentType.
type CreateVouchersJSONRequestBody = HotspotVoucherCreationRequest

// CreateNetworkJSONRequestBody defines body for CreateNetwork for application/json ContentType.
type CreateNetworkJSONRequestBody = CreateOrUpdateNetwork

// UpdateNetworkJSONRequestBody defines body for UpdateNetwork for application/json ContentType.
type UpdateNetworkJSONRequestBody = CreateOrUpdateNetwork

// CreateTrafficMatchingListJSONRequestBody defines body for CreateTrafficMatchingList for application/json ContentType.
type CreateTrafficMatchingListJSONRequestBody = CreateOrUpdateTrafficMatchingList

// UpdateTrafficMatchingListJSONRequestBody defines body for UpdateTrafficMatchingList for application/json ContentType.
type UpdateTrafficMatchingListJSONRequestBody = CreateOrUpdateTrafficMatchingList

// CreateWifiBroadcastJSONRequestBody defines body for CreateWifiBroadcast for application/json ContentType.
type CreateWifiBroadcastJSONRequestBody = WifiBroadcastCreateOrUpdate

// UpdateWifiBroadcastJSONRequestBody defines body for UpdateWifiBroadcast for application/json ContentType.
type UpdateWifiBroadcastJSONRequestBody = WifiBroadcastCreateOrUpdate
